### PR TITLE
Use redux-toolkit to manage redux layer

### PR DESCRIPTION
**Pull request by koorosh**
Initially, redux definitions like actions, action types and reducers were
declared manually with lots of code repetition and boilerplate which
didn't provide any flexibility or maintainability.

Current commit introduces following changes:
- code structure change for redux functionality. Reducers and sagas aren't
page specific anymore, they are defined as entities which can be reused by
any page. As a result redux functionality moved to `src/store` directory.
- Selectors can be global (if they provide higher level of transformations
or slice extraction) or as a page specific selectors which often depend on
provided props from a component and can't be easily reused in other components.
- `@redux-toolkit` is used to simplify writing of redux logic.
`createSlice` helper function is used to define both reducers and actions for
specific entity (like statements). Or `createAction` helper function to
define action, its expected payload.

In general, current project structure looks like:
```
- src
  - store
    - <entity>
      - <entity>.reducer.ts
      - <entity>.saga.ts
  -
```

PS: I apologize for single PR with dozens of file changes, many of them just moved to new place or changed import paths.

### CODE REVIEW

**Review by dhartunian — APPROVED** [review]
:lgtm: 

This is a really elegant refactor! Thank you @koorosh for putting the time and effort to clean all this up. I like these new patterns from redux toolkit a lot.

What do you think of also combining the sagas and `createSlice` definition together in one file? My concern is that the definitions are quite "far apart" in different files and it can be difficult to see what an action "does" just from reading the `createSlice` definition. Not a blocker to merging just want to have the conversation.

> Reviewed 53 of 53 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/admin-ui-components/45#-:-MO3HCir2htO7K4r-PeP:bj1hx0p)* status: all files reviewed, 3 unresolved discussions (waiting on @elkmaster, @koorosh, @nathanstilwell, and @nkodali)

___
*[src/statementsPage/statementsPageConnected.tsx, line 22 at r1](https://reviewable.io/reviews/cockroachdb/admin-ui-components/45#-MO3EZdP1sJexzNJWntZ:-MO3EZdP1sJexzNJWnt_:ba0ukes) ([raw file](https://github.com/cockroachdb/admin-ui-components/blob/a70d342c35e361ecfd9c92d8d47309de59e00b1a/src/statementsPage/statementsPageConnected.tsx#L22)):*
> ```XML
>   StatementsPageProps,
>   "statements" | "statementsError" | "apps" | "totalFingerprints" | "lastReset"
> >;
> ```

Is it worth separating the props for `StatementsPageProps` into a few different types that are then `union`-ed together instead?
___
*[src/statementsPage/statementsPageConnected.tsx, line 36 at r1](https://reviewable.io/reviews/cockroachdb/admin-ui-components/45#-MO3EhIWCwLd3_ul1sZR:-MO3EhIWCwLd3_ul1sZS:bel6ryh) ([raw file](https://github.com/cockroachdb/admin-ui-components/blob/a70d342c35e361ecfd9c92d8d47309de59e00b1a/src/statementsPage/statementsPageConnected.tsx#L36)):*
> ```XML
> >;
> 
> type OwnProps = Pick<StatementsPageProps, "onDiagnosticsReportDownload"> &
> ```

Yeah this ends up reading oddly because 
___
*[src/store/reducers.ts, line 16 at r1](https://reviewable.io/reviews/cockroachdb/admin-ui-components/45#-MO3F7p7A79R59VdIk_i:-MO3F7p7A79R59VdIk_j:b-cqxzvn) ([raw file](https://github.com/cockroachdb/admin-ui-components/blob/a70d342c35e361ecfd9c92d8d47309de59e00b1a/src/store/reducers.ts#L16)):*
> ```XML
> 
> export type AppState = {
>   adminUI: AdminUiState;
> ```

is this necessary to put under a separate layer? why not just have `AdminUiState` be the top level?

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/admin-ui-components/45)* status: 51 of 53 files reviewed, 3 unresolved discussions (waiting on @dhartunian, @elkmaster, @koorosh, @nathanstilwell, and @nkodali)

___
*[src/statementsPage/statementsPageConnected.tsx, line 36 at r1](https://reviewable.io/reviews/cockroachdb/admin-ui-components/45#-MO3EhIWCwLd3_ul1sZR:-MO7pXeZ3S7eYpvGq77d:bebrt1w) ([raw file](https://github.com/cockroachdb/admin-ui-components/blob/a70d342c35e361ecfd9c92d8d47309de59e00b1a/src/statementsPage/statementsPageConnected.tsx#L36)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Yeah this ends up reading oddly because 
</blockquote></details>

Will do
___
*[src/store/reducers.ts, line 16 at r1](https://reviewable.io/reviews/cockroachdb/admin-ui-components/45#-MO3F7p7A79R59VdIk_i:-MO7k280A4GzKYS8bVH1:b-2heaix) ([raw file](https://github.com/cockroachdb/admin-ui-components/blob/a70d342c35e361ecfd9c92d8d47309de59e00b1a/src/store/reducers.ts#L16)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

is this necessary to put under a separate layer? why not just have `AdminUiState` be the top level?
</blockquote></details>

This isolation allows to put all reducers under single slice from client app perspective. It stands more like namespace for reducers. 
Client application has to declare `adminUI` slice as a nested layer so admin ui specific reducers won't interfere with client app reducers.

```typescript
// client app code
type ClientAppStore = {
  clientAppReducer1: ...
  clientAppReducerN: ...
  adminUI: AdminUiState, // this is nested layer in client app
}

const store = combineReducers<RootStore>({ 
   ...
  adminUI: rootReducer,
})

```

**Comment by koorosh** [comment]
@dhartunian FYI: I've updated PR with changes according to your comments

**Review by dhartunian — APPROVED** [review]
:lgtm: 

> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/admin-ui-components/45#-:-MO8YLceDOj6AUl5xJZr:bg7igkv)* status: all files reviewed, 3 unresolved discussions (waiting on @elkmaster, @koorosh, @nathanstilwell, and @nkodali)

___
*[src/store/reducers.ts, line 16 at r1](https://reviewable.io/reviews/cockroachdb/admin-ui-components/45#-MO3F7p7A79R59VdIk_i:-MO8YGpi7XvJ3bosXUxT:bvf24k) ([raw file](https://github.com/cockroachdb/admin-ui-components/blob/a70d342c35e361ecfd9c92d8d47309de59e00b1a/src/store/reducers.ts#L16)):*
<details><summary><i>Previously, koorosh (Andrii Vorobiov) wrote…</i></summary><blockquote>

This isolation allows to put all reducers under single slice from client app perspective. It stands more like namespace for reducers. 
Client application has to declare `adminUI` slice as a nested layer so admin ui specific reducers won't interfere with client app reducers.

```typescript
// client app code
type ClientAppStore = {
  clientAppReducer1: ...
  clientAppReducerN: ...
  adminUI: AdminUiState, // this is nested layer in client app
}

const store = combineReducers<RootStore>({ 
   ...
  adminUI: rootReducer,
})

```

</blockquote></details>

excellent. thanks for the clarification.

**Pull request merged**
