### PR TITLE
Empty state for tables without data redesign

### PR DESCRIPTION
**Pull request by koorosh**
Currently, when some table on a page doesn't have data to display,
then Empty component rendered instead of a table and don't show
table headers.

Now, with the new design, EmptyState component should be rendered
inside table as a placeholder within table body.

To avoid any breaking changes, `EmptyState` component doesn't
replace `Empty` component.

### CODE REVIEW

**Review by dhartunian — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, 2 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/admin-ui-components/29)* status: 12 of 18 files reviewed, 4 unresolved discussions (waiting on @koorosh)

___
*[src/empty/empty.tsx, line 43 at r2](https://reviewable.io/reviews/cockroachdb/admin-ui-components/29#-MIVhA2q4SFkK3Z4KnHd:-MIVhA2q4SFkK3Z4KnHe:bf069h2) ([raw file](https://github.com/cockroachdb/admin-ui-components/blob/5b9dd554e2ffb8538b3f750eda76bbab68ba48d9/src/empty/empty.tsx#L43)):*
> ```XML
> 
> /**
>  * @deprecated use EmptyState instead
> ```

I'm a bit confused. We *just* added the `Empty` component earlier this year. I don't like replacing components so quickly. Can you explain why this was necessary? Why can't we just replace all usages of `Empty`?
___
*[src/emptyState/emptyState.tsx, line 15 at r1](https://reviewable.io/reviews/cockroachdb/admin-ui-components/29#-MIVgnK77d8pXlqaDpBL:-MIVgnK8EGBAWBYNvlhR:b-lx3q8l) ([raw file](https://github.com/cockroachdb/admin-ui-components/blob/f0d8b5ca3beb26f99df8a42d17b5d46d7fccfcd1/src/emptyState/emptyState.tsx#L15)):*
> ```XML
> const cx = classNames.bind(styles);
> 
> export const EmptyState: React.FC<EmptyStateProps> = ({
> ```

Can you add a comment describing what this component is to be used for. Should it always go inside a table, for instance? I would like to disambiguate with usage of `Empty`. 
___
*[src/icon/backIcon.tsx, line 20 at r2](https://reviewable.io/reviews/cockroachdb/admin-ui-components/29#-MIVhLU6CUjI9ZfYTFC4:-MIVhLU6CUjI9ZfYTFC5:bpvx0vj) ([raw file](https://github.com/cockroachdb/admin-ui-components/blob/02e71e7ecdd90e4c18630ab4181db622d1e7e702/src/icon/backIcon.tsx#L20)):*
> ```XML
> const cx = classNames.bind(styles);
> 
> // tslint:disable-next-line: variable-name
> ```

Thanks for cleaning this up.
___
*[src/statementsPage/statementsPage.tsx, line 276 at r2](https://reviewable.io/reviews/cockroachdb/admin-ui-components/29#-MIVhrYF3eak-MUqyPrs:-MIVhrYF3eak-MUqyPrt:b-qzgtm0) ([raw file](https://github.com/cockroachdb/admin-ui-components/blob/5b9dd554e2ffb8538b3f750eda76bbab68ba48d9/src/statementsPage/statementsPage.tsx#L276)):*
> ```XML
>     }
>   };
> ```

Can we extract this into a named functional component? `StatementsEmpty` or something?

**Review by nathanstilwell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/admin-ui-components/29)* status: 12 of 18 files reviewed, 4 unresolved discussions (waiting on @dhartunian and @koorosh)

___
*[src/empty/empty.tsx, line 43 at r2](https://reviewable.io/reviews/cockroachdb/admin-ui-components/29#-MIVhA2q4SFkK3Z4KnHd:-MIX1MSz4mgn3beU12dG:b-itq6t5) ([raw file](https://github.com/cockroachdb/admin-ui-components/blob/5b9dd554e2ffb8538b3f750eda76bbab68ba48d9/src/empty/empty.tsx#L43)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

I'm a bit confused. We *just* added the `Empty` component earlier this year. I don't like replacing components so quickly. Can you explain why this was necessary? Why can't we just replace all usages of `Empty`?
</blockquote></details>

Looking at the designs for "Empty States" I think I can see a need for this kind of component (https://www.figma.com/file/uU9C1XSleeAu26CvTWwekX/obsrv_admin-ui-empty-states?node-id=128%3A0). But I agree with David that we may need to deprecate some of our "Empty" components or at least consolidate the functionality into one component that will serve up friendly empty states for all cases across the application.

**Review by nathanstilwell — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, 6 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/admin-ui-components/29)* status: all files reviewed, 6 unresolved discussions (waiting on @dhartunian and @koorosh)

___
*[src/emptyState/emptyState.tsx, line 7 at r1](https://reviewable.io/reviews/cockroachdb/admin-ui-components/29#-MIa-5q15b_VxaSzOSk4:-MIa-5q2-19kYHqVDmBc:b-b0tpx3) ([raw file](https://github.com/cockroachdb/admin-ui-components/blob/f0d8b5ca3beb26f99df8a42d17b5d46d7fccfcd1/src/emptyState/emptyState.tsx#L7)):*
> ```XML
> 
> export interface EmptyStateProps {
>   icon?: string;
> ```

Could we extend this prop type to be either a string of a ReactNode? I'm thinking about the case where I might want to pass in an [Icon](https://github.com/cockroachdb/ui/tree/master/packages/ui-components/src/Icon) component rather than a raw SVG. I could also see waiting until we extend the Icon component to support the illustrative images.
___
*[src/emptyState/emptyState.tsx, line 15 at r1](https://reviewable.io/reviews/cockroachdb/admin-ui-components/29#-MIVgnK77d8pXlqaDpBL:-MI_zFsVClAmXwRWgCRk:bq5dyky) ([raw file](https://github.com/cockroachdb/admin-ui-components/blob/f0d8b5ca3beb26f99df8a42d17b5d46d7fccfcd1/src/emptyState/emptyState.tsx#L15)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Can you add a comment describing what this component is to be used for. Should it always go inside a table, for instance? I would like to disambiguate with usage of `Empty`. 
</blockquote></details>

Looking at the mocks for empty states and how they will be used, I think this component is quite well suited to provide for those states. Having said that, I think David is right about providing a comment block for this component as it may not be immediately obvious at first glance. 
___
*[src/statementsPage/statementsPage.tsx, line 276 at r2](https://reviewable.io/reviews/cockroachdb/admin-ui-components/29#-MIVhrYF3eak-MUqyPrs:-MIa1Ah44fBaYO65g3OC:b-2glnvg) ([raw file](https://github.com/cockroachdb/admin-ui-components/blob/5b9dd554e2ffb8538b3f750eda76bbab68ba48d9/src/statementsPage/statementsPage.tsx#L276)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Can we extract this into a named functional component? `StatementsEmpty` or something?
</blockquote></details>

+1 for breaking up this file a little more.
___
*[src/transactionsPage/transactionsPage.tsx, line 176 at r2](https://reviewable.io/reviews/cockroachdb/admin-ui-components/29#-MIa3OFS-aGBZvvEiS3N:-MIa3OFT0nUwvzf4f1UD:b2leutd) ([raw file](https://github.com/cockroachdb/admin-ui-components/blob/5b9dd554e2ffb8538b3f750eda76bbab68ba48d9/src/transactionsPage/transactionsPage.tsx#L176)):*
> ```XML
>   };
> 
>   noTransactionsResult = () => {
> ```

This might also be another opportunity to extract a _EmptyTransactionsResult_ component.

**Review by koorosh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/admin-ui-components/29)* status: 11 of 20 files reviewed, 6 unresolved discussions (waiting on @dhartunian and @nathanstilwell)

___
*[src/empty/empty.tsx, line 43 at r2](https://reviewable.io/reviews/cockroachdb/admin-ui-components/29#-MIVhA2q4SFkK3Z4KnHd:-MIt0N2_0k1Z59gFwcri:bwvn32x) ([raw file](https://github.com/cockroachdb/admin-ui-components/blob/5b9dd554e2ffb8538b3f750eda76bbab68ba48d9/src/empty/empty.tsx#L43)):*
<details><summary><i>Previously, nathanstilwell (Nathan Stilwell) wrote…</i></summary><blockquote>

Looking at the designs for "Empty States" I think I can see a need for this kind of component (https://www.figma.com/file/uU9C1XSleeAu26CvTWwekX/obsrv_admin-ui-empty-states?node-id=128%3A0). But I agree with David that we may need to deprecate some of our "Empty" components or at least consolidate the functionality into one component that will serve up friendly empty states for all cases across the application.
</blockquote></details>

I didn't find a good way to fuse these two kinds of "empty components" into one component.
In general they look very similar and serve the same logic, but their visual appearance very different. My concern about having one component for both cases is that such component might have many props where some of them are used to show empty table state and other props for another case. 
For instance, old `Empty` component shows `icon` prop as background image positioned to the top-right corner on top of white background. And "new" Empty component serves `icon` prop as foreground image in the middle of container. To have a generic component which satisfy both cases we might need to expose very specific props to customize component:
```typescript
interface EmptyProps {
  image: "string" | "ReactNode";
  backgroundColor: "string";
  imagePosition: "top" | "topRight" | "center" | ...
  ...
}

```


Would it be an option to define following components structure where under some common "Empty" object (served as an umbrella) will be nested specific components: `EmptyPanel` and `EmptyTable`?
```typescript

export const Empty = {
  EmptyTable,
  EmptyPanel, // current <Empty /> component
}

```
___
*[src/icon/backIcon.tsx, line 20 at r2](https://reviewable.io/reviews/cockroachdb/admin-ui-components/29#-MIVhLU6CUjI9ZfYTFC4:-MIxEs8NEKvUjEK53aZN:b-vocqru) ([raw file](https://github.com/cockroachdb/admin-ui-components/blob/02e71e7ecdd90e4c18630ab4181db622d1e7e702/src/icon/backIcon.tsx#L20)):*
<details><summary><i>Previously, dhartunian (David Hartunian) wrote…</i></summary><blockquote>

Thanks for cleaning this up.
</blockquote></details>

👍🏽
___
*[src/statementsPage/statementsPage.tsx, line 276 at r2](https://reviewable.io/reviews/cockroachdb/admin-ui-components/29#-MIVhrYF3eak-MUqyPrs:-MIxE2gs6rqRjc8YhuNU:bb6un1j) ([raw file](https://github.com/cockroachdb/admin-ui-components/blob/5b9dd554e2ffb8538b3f750eda76bbab68ba48d9/src/statementsPage/statementsPage.tsx#L276)):*
<details><summary><i>Previously, nathanstilwell (Nathan Stilwell) wrote…</i></summary><blockquote>

+1 for breaking up this file a little more.
</blockquote></details>

Done
___
*[src/transactionsPage/transactionsPage.tsx, line 176 at r2](https://reviewable.io/reviews/cockroachdb/admin-ui-components/29#-MIa3OFS-aGBZvvEiS3N:-MIxEngI6w784QJ8GXIZ:bb6un1j) ([raw file](https://github.com/cockroachdb/admin-ui-components/blob/5b9dd554e2ffb8538b3f750eda76bbab68ba48d9/src/transactionsPage/transactionsPage.tsx#L176)):*
<details><summary><i>Previously, nathanstilwell (Nathan Stilwell) wrote…</i></summary><blockquote>

This might also be another opportunity to extract a _EmptyTransactionsResult_ component.
</blockquote></details>

Done
___
*[src/emptyState/emptyState.tsx, line 7 at r1](https://reviewable.io/reviews/cockroachdb/admin-ui-components/29#-MIa-5q15b_VxaSzOSk4:-MIwcH2M68TSIIkPjV3C:b-80tlqx) ([raw file](https://github.com/cockroachdb/admin-ui-components/blob/f0d8b5ca3beb26f99df8a42d17b5d46d7fccfcd1/src/emptyState/emptyState.tsx#L7)):*
<details><summary><i>Previously, nathanstilwell (Nathan Stilwell) wrote…</i></summary><blockquote>

Could we extend this prop type to be either a string of a ReactNode? I'm thinking about the case where I might want to pass in an [Icon](https://github.com/cockroachdb/ui/tree/master/packages/ui-components/src/Icon) component rather than a raw SVG. I could also see waiting until we extend the Icon component to support the illustrative images.
</blockquote></details>

Sure!
___
*[src/emptyState/emptyState.tsx, line 15 at r1](https://reviewable.io/reviews/cockroachdb/admin-ui-components/29#-MIVgnK77d8pXlqaDpBL:-MIwd0oq4I8cJWc6ROEi:b-welnxw) ([raw file](https://github.com/cockroachdb/admin-ui-components/blob/f0d8b5ca3beb26f99df8a42d17b5d46d7fccfcd1/src/emptyState/emptyState.tsx#L15)):*
<details><summary><i>Previously, nathanstilwell (Nathan Stilwell) wrote…</i></summary><blockquote>

Looking at the mocks for empty states and how they will be used, I think this component is quite well suited to provide for those states. Having said that, I think David is right about providing a comment block for this component as it may not be immediately obvious at first glance. 
</blockquote></details>

Agree. Indeed, this component can be used everywhere and it might be used outside of table technically, but "by design" it's a placeholder for empty tables for sure! I will add description and rename component to `EmptyTablePlaceholder`.

**Pull request merged**
