### PR TITLE
extend Diagnostics column for statements page

### PR DESCRIPTION
**Pull request by koorosh**
Related to https://github.com/cockroachdb/cockroach/issues/50824

Previously, statement diagnostics could only be triggered from
Statements page and it wasn't possible to download. Also when
first diagnostics report is generated, then `Activate` button
wasn't available at all.

Now, Diagnostics column allows users to request diagnostics
reports when all previous reports are generated and allow
to download all previously generated reports from the list.

Screen Shot 2020-10-01 at 4 55 32 PM

With rewritten Dropdown component, it is necessary to
adjust its usage across the current package.
Currently, it is used only in one place so this changes
aren't global.

Screen Shot 2020-10-01 at 4 55 16 PM

### CODE REVIEW

**Comment by elkmaster** [comment]
@koorosh, trying it out locally, keep getting such error:
Screenshot 2020-10-12 at 17 28 40

**Comment by koorosh** [comment]
> @koorosh, trying it out locally, keep getting such error:

`statements` page in Storybooks requires connected backend to work.
```
TARGET=http://localhost:8080 yarn storybook
```
where cockroachdb is run locally on :8080 port
Please, check if it helps to resolve this issue

**Review by nathanstilwell — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/admin-ui-components/31)* status: all files reviewed, 1 unresolved discussion (waiting on @dhartunian, @elkmaster, and @koorosh)

*[a discussion](https://reviewable.io/reviews/cockroachdb/admin-ui-components/31#-MJXd5Jp9z0bfpxpPdwU:-MJXd5Jp9z0bfpxpPdwV:b-nrn8x3) (no related file):*
I guess there's not great time to start this conversation, but is it possible to replace the `Button` component in `admin-ui-components` with `Button` from `cockroachdb/ui`? That should ensure we are consistent with latest designs. If some functionality is missing or inadequate I would at least like to know.

There are also some instances where I think we could begin integrating the values found in our [design tokens](https://github.com/cockroachdb/ui/tree/master/packages/design-tokens). I'm only going to leave this feedback as a comment for now, as I don't want to hold up this work. But this is making me realize that we should discuss how we can start consolidating components in our work going forward.

---

**Comment by koorosh** [comment]
> > Reviewed 3 of 3 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, 9 of 9 files at r4.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/admin-ui-components/31)_ status: all files reviewed, 1 unresolved discussion (waiting on @dhartunian, @elkmaster, and @koorosh)
> 
> _[a discussion](https://reviewable.io/reviews/cockroachdb/admin-ui-components/31#-MJXd5Jp9z0bfpxpPdwU:-MJXd5Jp9z0bfpxpPdwV:b-nrn8x3) (no related file):_
> I guess there's not great time to start this conversation, but is it possible to replace the `Button` component in `admin-ui-components` with `Button` from `cockroachdb/ui`? That should ensure we are consistent with latest designs. If some functionality is missing or inadequate I would at least like to know.
> 
> There are also some instances where I think we could begin integrating the values found in our [design tokens](https://github.com/cockroachdb/ui/tree/master/packages/design-tokens). I'm only going to leave this feedback as a comment for now, as I don't want to hold up this work. But this is making me realize that we should discuss how we can start consolidating components in our work going forward.

@nathanstilwell , you're absolutely right `cockroachdb/ui` has to be the primary source for components and design tokens!
In this case, `Button` component (from `admin-ui-components` repo) has extended functionality to handle rendering of icons, rest of logic looks mostly the same. 
I will check if it's possible to use `cockroachdb/ui` component here without extra changes in <Button> component, otherwise keep current implementation.

**Pull request merged**
